services:
  payments-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orcha-payments-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "OrchaPassword123!"
      MSSQL_PID: "Developer"
    ports:
      - "1436:1433"
    volumes:
      - ./seed.sql:/usr/config/seed.sql
      - ./entrypoint.sh:/usr/config/entrypoint.sh
    entrypoint: /bin/bash /usr/config/entrypoint.sh
