services:
  items-db:
    image: postgres:15-alpine
    container_name: orcha-items-pg
    environment:
      POSTGRES_USER: orcha
      POSTGRES_PASSWORD: orcha_password
      POSTGRES_DB: items_service
    ports:
      - "5433:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
