services:
  orders-db:
    image: mysql:8.0
    container_name: orcha-orders-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders_service
      MYSQL_USER: orcha
      MYSQL_PASSWORD: orcha_password
    ports:
      - "3307:3306"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
