services:
  postgres:
    image: postgres:15-alpine
    container_name: orcha-postgres
    restart: always
    environment:
      POSTGRES_USER: orcha
      POSTGRES_PASSWORD: OrchaAgentOS!2025
      POSTGRES_DB: orcha_test
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: orcha-pg-network
