services:
  customer-db:
    image: postgres:15-alpine
    container_name: orcha-customer-pg
    environment:
      POSTGRES_USER: orcha
      POSTGRES_PASSWORD: orcha_password
      POSTGRES_DB: customer_service
    ports:
      - "5434:5432"
    volumes:
      - ./customer/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

  items-db:
    image: postgres:15-alpine
    container_name: orcha-items-pg
    environment:
      POSTGRES_USER: orcha
      POSTGRES_PASSWORD: orcha_password
      POSTGRES_DB: items_service
    ports:
      - "5433:5432"
    volumes:
      - ./items/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

  orders-db:
    image: mysql:8.0
    container_name: orcha-orders-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders_service
      MYSQL_USER: orcha
      MYSQL_PASSWORD: orcha_password
    ports:
      - "3307:3306"
    volumes:
      - ./order/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

  payments-db:
    image: mysql:8.0
    container_name: orcha-payments-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: payments_service
      MYSQL_USER: orcha
      MYSQL_PASSWORD: orcha_password
    ports:
      - "3308:3306"
    volumes:
      - ./payments/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped

  reviews-db:
    image: postgres:15-alpine
    container_name: orcha-reviews-pg
    environment:
      POSTGRES_USER: orcha
      POSTGRES_PASSWORD: orcha_password
      POSTGRES_DB: reviews_service
    ports:
      - "5435:5432"
    volumes:
      - ./reviews/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    restart: unless-stopped
